server:
  servlet:
    context-path: /api
spring:
  cassandra:
    schema-action: create_if_not_exists
    keyspace-name: authdb
    contact-points: grailsfm-auth-db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
