server:
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    mongodb:
      host: localhost
      port: 9501
      database: songdb
      username: ${DB_USER}
      password: ${DB_PASSWORD}