services:
  grailsfm-artist-db:
    container_name: grailsfm-artist-db
    image: mongo:7.0
    ports:
      - "9401:27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_DATABASE=artistdb
    restart: always
